# Generated by Django 4.1.6 on 2023-03-25 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendShip',
            fields=[
                ('frId', models.BigAutoField(help_text='Friendship ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.BigAutoField(help_text='Message ID', primary_key=True, serialize=False)),
                ('isRead', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('frId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagePost', to='relation.friendship')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagePost', to=settings.AUTH_USER_MODEL, to_field='userName')),
            ],
        ),
        migrations.CreateModel(
            name='FUser',
            fields=[
                ('fuId', models.BigAutoField(help_text='FUser ID', primary_key=True, serialize=False)),
                ('otherUser', models.IntegerField()),
                ('frId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fUserPost', to='relation.friendship')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fUserPost', to=settings.AUTH_USER_MODEL, to_field='userName')),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('alarmId', models.BigAutoField(help_text='Alarm ID', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('typeId', models.IntegerField()),
                ('isRead', models.BooleanField(default=False)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('fromUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AlarmFromUserPost', to=settings.AUTH_USER_MODEL, to_field='userName')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AlarmUserPost', to=settings.AUTH_USER_MODEL, to_field='userName')),
            ],
        ),
    ]
